# create a role for ec2 instance, attach a role 👇
# policy name AmazonEC2RoleforAWSCodeDeploy
version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/myapp
hooks:
  BeforeInstall:
    - location: codedeploy/install_node.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: codedeploy/deploy.sh
      timeout: 100
      runas: root